apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx  # ← Must match base deployment name
spec:
  replicas: 1
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
      - name: nginx
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace