apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-prod

resources:
- ../../base

patchesStrategicMerge:
- patch.yaml

commonLabels:
  environment: prod

namePrefix: prod-