apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-prod

resources:
- ../../base

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: nginx

labels:
- pairs:
    environment: prod
    tier: production

namePrefix: prod-