apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nginx-base

resources:
- deployment.yaml
- service.yaml

# Modern syntax - no deprecation warnings
labels:
- pairs:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/managed-by: argocd