apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        replicas: "1"
      - env: staging
        replicas: "2"
      - env: prod  
        replicas: "3"
  template:
    metadata:
      name: 'nginx-{{env}}'
      labels:
        environment: '{{env}}'
        generator: 'applicationset'
    spec:
      project: demo-project
      source:
        # Using working public repo for demo
        repoURL: 'https://github.com/mdsraihaniqbal1999/argocd-applicationsets-demo'
        targetRevision: HEAD
        path: 'guestbook'  # Simple working example
      destination:
        server: https://kubernetes.default.svc
        namespace: 'nginx-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
